# Generated by Django 5.2.8 on 2025-11-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="binding_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
