# Generated by Django 5.2.8 on 2025-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_telegramprofile_binding_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramprofile",
            name="chat_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="telegramprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chat_id", None), _negated=True),
                fields=("chat_id",),
                name="unique_chat_id_not_null",
            ),
        ),
    ]
