# Generated by Django 5.2.8 on 2025-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_telegramprofile_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
