# Generated by Django 5.2.8 on 2025-11-24 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
                ("time_of_day", models.TimeField()),
                ("is_pleasant", models.BooleanField(default=False)),
                (
                    "reward_text",
                    models.CharField(
                        blank=True, help_text="Текстовая награда, если не pleasant habit.", max_length=255, null=True
                    ),
                ),
                (
                    "periodicity_days",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1 день."), (2, "2 дня."), (3, "3 дня."), (5, "5 дней."), (7, "7 дней.")],
                        default=1,
                        help_text="1, 2, 3, 5, 7 дней.",
                    ),
                ),
                (
                    "repeat_limit",
                    models.PositiveSmallIntegerField(
                        choices=[(21, "Стандарт 21 повтор"), (30, "Челендж 30 повторов"), (45, "Марафон 45 повторов")],
                        default=21,
                        help_text="21, 30, 45 повторов.",
                    ),
                ),
                ("grace_minutes", models.PositiveIntegerField()),
                ("fix_minutes", models.PositiveIntegerField()),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_pleasant_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка – награда.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_for",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
