# Generated by Django 5.2.8 on 2025-11-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="fix_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="habit",
            name="grace_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1 день."), (2, "2 дня."), (3, "3 дня."), (5, "5 дней."), (7, "7 дней.")],
                default=1,
                help_text="1, 2, 3, 5, 7 дней.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="repeat_limit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(21, "Стандарт 21 повтор"), (30, "Челендж 30 повторов"), (45, "Марафон 45 повторов")],
                default=21,
                help_text="21, 30, 45 повторов.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_of_day",
            field=models.TimeField(default="00:00"),
        ),
    ]
