# Generated by Django 5.2.8 on 2025-11-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_fix_minutes_alter_habit_grace_minutes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity_days",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1 день."), (2, "2 дня."), (3, "3 дня."), (5, "5 дней."), (7, "7 дней.")],
                default=1,
                help_text="1, 2, 3, 5, 7 дней.",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="repeat_limit",
            field=models.PositiveSmallIntegerField(
                choices=[(21, "Стандарт 21 повтор"), (30, "Челендж 30 повторов"), (45, "Марафон 45 повторов")],
                default=21,
                help_text="21, 30, 45 повторов.",
            ),
        ),
    ]
