# Generated by Django 5.2.8 on 2025-11-30 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_periodicity_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_of_day",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
