# Generated by Django 5.2.8 on 2025-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HabitInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_datetime", models.DateTimeField()),
                ("confirm_deadline", models.DateTimeField()),
                ("fix_deadline", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("completed_late", "Completed Late"),
                            ("missed", "Missed"),
                            ("fix_expired", "Fix Expired"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["scheduled_datetime"],
            },
        ),
    ]
