# Generated by Django 5.2.8 on 2025-11-24 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habit_instances", "0001_initial"),
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitinstance",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="instances", to="habits.habit"
            ),
        ),
        migrations.AddIndex(
            model_name="habitinstance",
            index=models.Index(fields=["status"], name="habit_insta_status_5dd5bf_idx"),
        ),
        migrations.AddIndex(
            model_name="habitinstance",
            index=models.Index(fields=["scheduled_datetime"], name="habit_insta_schedul_60dc6b_idx"),
        ),
    ]
